module.exports = {
    production: {
        port: '5005',
        website: {host: 'localhost', port: 8080},
        api: {host: 'localhost', port: 8080},
        redisURL: 'redis://localhost:6379',
        cache: false,
        protocol : "http"
    },
    
    development: {
        port: '5005',
        // website: {host: 'sudarshannews.com', port: 80},
        // api: {host: 'sudarshannews.com', port: 80},
         // website: {host: 'hocalwire.allytechnologies.in', port: 80},
         // api: {host: 'hocalwire.allytechnologies.in', port: 80},
        // api: {host: 'millenniumpost.in', port: 80},
        // website: {host: 'millenniumpost.in', port: 80},
        // website: {host: 'naradanews.com', port: 80},
        // api: {host: 'naradanews.com', port: 80},
        // website: {host: 'millenniumpost.in', port: 80},
        // api: {host: 'royalsite.vocalwire.com', port: 80},
        // website: {host: 'apnnews.com', port: 80},
        // api: {host: 'apnnews.com', port: 80},
        // website: {host: 'pninewshisite.vocalwire.com', port: 80},
        // api: {host: 'pninewshisite.vocalwire.com', port: 80},
         api: {host: 'hocalwire.com', port: 80},
         website: {host: 'hocalwire.com', port: 80},
        //website: {host: 'apnnews.com', port: 80},
        //api: {host: 'apnnews.com', port: 80},
        // website: {host: 'pninewshisite.vocalwire.com', port: 80},
        // api: {host: 'pninewshisite.vocalwire.com', port: 80},
        // website: {host: 'indiaprojectsnews.in', port: 80},
        // api: {host: 'indiaprojectsnews.in', port: 80},
        //website: {host: 'royalsite.vocalwire.com', port: 80},
        //api: {host: 'royalsite.vocalwire.com', port: 80},
        // website: {host: 'apnnews.com', port: 80},
        // api: {host: 'apnnews.com', port: 80},
        // website: {host: 'apnnewssite.vocalwire.com', port: 80},
        // api: {host: 'apnnewssite.vocalwire.com', port: 80},
        //website: {host: 'vocalwire.com', port: 80},
        //api: {host: 'vocalwire.com', port: 80},
        // website: {host: 'cms.nnscommoditynews.com', port: 80},
        // api: {host: 'cms.nnscommoditynews.com', port: 80},
        // website: {host: 'pninewshisite.vocalwire.com', port: 80},
        // api: {host: 'pninewshisite.vocalwire.com', port: 80},
        // website: {host: 'naradanews.com', port: 80},
        // api: {host: 'naradanews.com', port: 80},
        // website: {host: 'allytechnologies.in', port: 80},
        // api: {host: 'allytechnologies.in', port: 80},
        // website: {host: 'thehawk.in', port: 80},
        // api: {host: 'thehawk.in', port: 80},
        // website: {host: 'specialcoveragenews.in', port: 80},
        // api: {host: 'specialcoveragenews.in', port: 80},
        //website: {host: 'specialcoveragenews.in', port: 80},
        //api: {host: 'specialcoveragenews.in', port: 80},
        // website: {host: 'specialcoveragenews.in', port: 80},
        // api: {host: 'specialcoveragenews.in', port: 80},
         // website: {host: 'pninewssite.vocalwire.com', port: 80},
         // api: {host: 'pninewssite.vocalwire.com', port: 80},
         //website: {host: 'pninewssite.vocalwire.com', port: 80},
         //api: {host: 'pninewssite.vocalwire.com', port: 80},
        redisURL: 'redis://localhost:6379',
        cache: false,
        protocol : "http"
    }
};
