var PartnerConfig = {
    "partner1" : {
        "domains" : ["www.partner1.com","partner1.com"],
        "langs" : ["en","hi"],
        "protocals" : ["http","https"],
        "sessionId" : "RDWEBYNZC3JGAQLRUWGUUR2OWDEARR3DDWTQI"
        // "cacheRegex" : '[\\w]*\\/[\\w-]+\\-([0-9]+)',
    },

    "partner2" : {
        "domains" : ["www.partner2.com","partner2.com"],
        "langs" : ["en","ta"],
        "protocals" : ["http","https"],
        "sessionId" : "RDWEBHVSLJCJ1LDOXOQS6FLM2YCZP6G9FFYKF",
        "cacheRegex" : '/[\\w]*\\-([0-9]+)',
        "staticCacheUrls" : "/404,/error,/aboutus,/careers",
        "cache" : false
    },
    "specialcoveragenews" : {
            "domains" : ["en.specialcoveragenews.in","specialcoveragenews.com","www.specialcoveragenews.com","specialcoveragesite.hocalwire.com","specialcoveragenewssite1.hocalwire.com","specialcoveragenewslocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB8UTZAO06JTE9BQOIGVNZRQUEHLWNPPD9",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "specialcoveragehindi" : {
            "domains" : ["specialcoveragenews.in","www.specialcoveragenews.in","specialcoveragenewssite2.hocalwire.com","specialcoveragehindisite.hocalwire.com","lonoti.com","specialcoveragehindilocal.in"], 
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDANDROIDHOCAL355289067108183",//RDWEB8QOWPZV8C7REZDMGXO4DCUPE43JNEWNV
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/about-us,/contact-us",
            "cache" : false,
            "hasAuthors" : true,
            "mediaType" : "Online",
            // "CDNURL" : "http://cloud.specialcoveragenews.in/"
    },
    "demo1" : {
            "domains" : ["www.demo1.hocalwire.com","www.demo1.com","demo1.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBHZ2D0AGPONJR4MQT9OTUUZJ9O23FGVVU",
            "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "",
            "cache" : false,
            "mediaType" : "Demo"
    },
    "demo2" : {
            "domains" : ["www.demo2.hocalwire.com","www.demo2.com","demo2.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBBJKIFCBPWSM85JOJPAFSFFKSKIWLIG4Q",
            "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "",
            "cache" : false,
        "mediaType" : "Demo"
    },
    "jantakiawaz" : {
            "domains" : ["www.jantakiawaz.org","jantakiawaz.org","jantakiawazsite.vocalwire.com","www.jantakiawazsite.vocalwire.com","jantakiawazsite.hocalwire.com","jantakiawazlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJSA4LLAGYXITWJS5ZLMRZQEYSMDYSKA4",
            "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "",
            "cache" : false,
            "mediaType" : "Online",
            "CDNURL" : "http://cloud.jantakiawaz.org/"
    },
    "demo" : {
            "domains" : ["demosite.hocalwire.com","www.demosite.com","demosite.com","demosite.vocalwire.com","www.demosite.hocalwire.com","www.demosite.vocalwire.com","demolocal.com","www.demolocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBYTW5ZKISKLDOOQRPOAZBUEKL99VNKX0V",
            "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "",
            "cache" : false,
        "mediaType" : "Demo"
    },
    "vyaparkesari" : {
                "domains" : ["www.vyaparkesari.com","vyaparkesari.com","vyaparkesarisite.vocalwire.com","www.vyaparkesarisite.vocalwire.com","vyaparkesarisite.hocalwire.com","www.vyaparkesarisite.hocalwire.com","vyaparkesarilocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDANDROIDVYAPARKESARID564C9C63809B6E8",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "contentTypes" : ["news","trends","forecast","featured"],
                "hasPaidContent":true,
                "staticCacheUrls" : "",
                "cache" : false,
                "hasLogin" : true,
                "mediaType": "paid"
    },
    "ugtabharat" : {
                "domains" : ["www.ugtabharat.com","ugtabharatlocal.com","ugtabharat.com","ugtabharatsite.vocalwire.com","www.ugtabharatsite.vocalwire.com","ugtabharatsite.hocalwire.com","www.ugtabharatsite.hocalwire.com","ugtabharatsite.com","www.ugtabharatsite.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBMEOI9CCD9QNIVPC0DMY1FLNIMZZI5PUJ",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
                "mediaType" : "Print",
                "CDNURL" : "http://cloud.ugtabharat.com/"
        },
    "a2znews" : {
                "domains" : ["www.a2znewschannel.com","a2znewschannel.com","site.a2znewschannel.com","a2znewschannellocal.com","a2znewssite.vocalwire.com","www.a2znewssite.vocalwire.com","a2znewssite.hocalwire.com","www.a2znewssite.hocalwire.com","a2znewssite.com","www.a2znewssite.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB2G59DRKEGQ5UUNCSZJG55YAXHOXIPPW1",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "TV"
    },
    "meridelhi" : {
                "domains" : ["www.meridelhi.com","meridelhi.com","meridelhilocal.com","meridelhisite.vocalwire.com","www.meridelhisite.vocalwire.com","meridelhisite.hocalwire.com","www.meridelhisite.hocalwire.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB9O0O9GIDYLVWRCG1IGTTXS7GNXY2B0SJ",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false
    },
    "arnavbharat" : {
                "domains" : ["www.arnavbharat.org","arnavbharat.org","arnavbharatlocal.org","arnavbharatsite.vocalwire.com","arnavbharatsite.hocalwire.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBPLFBACRX9T8QAVLIARSW8UGRSFCMGP1N",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Print"
    },
    "webvarta" : {
                "domains" : ["www.webvarta.com","webvarta.com","webvartalocal.com","webvartasite.vocalwire.com","www.webvartasite.vocalwire.com","webvartasite.hocalwire.com","www.webvartasite.hocalwire.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB4HVSCC0AO8I7HA4TONVPU0O4LJMTOZKE",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "hasLogin" : true,
        "mediaType" : "demo"
    },
    "v4j" : {
                "domains" : ["www.v4jsite.hocalwire.com","v4jsite.hocalwire.com","www.v4jsite.vocalwire.com","v4jsite.vocalwire.com","v4jlocal.com","www.v4jlocal.com"],
                "langs" : ["en","tn"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBQXCLM7ZABIUVR5BU0OJSVNMXR3MNNWK1",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Online"
    },
    "v4jta" : {
                "domains" : ["www.v4jtasite.hocalwire.com","v4jtasite.hocalwire.com","www.v4jtasite.vocalwire.com","v4jtasite.vocalwire.com","v4jtalocal.com","www.v4jtalocal.com"],
                "langs" : ["en","tn"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBL2L0ITKZ8GYF53V7UHAIIWCLSAPOOUOB",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false
    },
    "vijayavani" : {
                "domains" : ["www.vijayavanisite.hocalwire.com","vijayavanisite.hocalwire.com","www.vijayavanisite.vocalwire.com","vijayavanisite.vocalwire.com","vijayavanilocal.com","www.vijayavanilocal.com"],
                "langs" : ["ka"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBXFS3SZI6QYMXN7UIPOHBZ7BNOBWDQIOF",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false
    },
    "womentimes" : {
                "domains" : ["womentimes.in","www.womentimes.in","womentimessite.hocalwire.com","womentimeslocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBFUTQNO6IKZAVYMH0YRYMK0XAG7R2JSSZ",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "contentTypes" : ["reporter"],
                "hasAuthors" : false,
                "inlineVideos" : true,
                "mediaType" : "TV"
    },
    "domex" : {
                "domains" : ["www.indiaprojectsnews.in","indiaprojectsnews.in","domex.hocalwire.com","domexsite.vocalwire.com","www.domexsite.vocalwire.com","domexlocal.com","domexsite.allytechnologies.in"],
                "langs" : ["en","tn"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBTPXCXOKCNQCDP9DI6QAD0WZK6SXMDLXC",//RDWEBTPXCXOKCNQCDP9DI6QAD0WZK6SXMDLXC",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "hasLogin" : true,
                "contentTypes" : ["projects","news","orders","companies","persons","location","phases","projectlocation","phaseapprovals","phaseproducts","notice_board","profile_extra_info"],
                "hasPaidContent" :true,
                "newsCategoryListingPrimaryContentType" : "1",
                "CDNURL" : "http://cloud.allytechnologies.in/",
                "defaultCategoryPageCount" : 10,
                "mediaType" : "paid",
                "locationsParentId":183
    },
    "newsmx" : {
                "domains" : ["www.newsmx.tv","newsmx.tv","newsmxlocal.tv","newsmxsite.hocalwire.com"],
                "langs" : ["en","tn"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBC6OQZTGGFVH9JZ54ZCXOXLKMNGLRMLX8",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "inlineVideos" : true,
        "mediaType" : "TV"
    },
    "bharatkaujala" : {
                "domains" : ["bharatkaujala.com","www.bharatkaujala.com","bharatkaujalasite.hocalwire.com","bharatkaujalalocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBSGVG1TTNOAAQAN5KAYTUBDE4WOPTZNBO",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "mediaType" : "Print",
                "CDNURL" : "http://cloud.bharatkaujala.com/"
    },
    "thehawk" : {
                "domains" : ["www.thehawk.in","thehawksite.vocalwire.com","thehawk.in","thehawksite.hocalwire.com","www.thehawksite.hocalwire.com","www.thehawksite.vocalwire.com","thehawklocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBD9ZXBMHEVOZY44KG0ZIGGJKEI9YBQY0U",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
                "mediaType" : "Print",
                "CDNURL" :"http://cloud.thehawk.in/"
    },
    "thehawkhi" : {
                "domains" : ["www.dainikhawk.com","dainikhawk.com","hindi.thehawk.in","thehawkhisite.vocalwire.com","hindi.thehawk.in","thehawkhisite.hocalwire.com","www.thehawkhisite.hocalwire.com","www.thehawkhisite.vocalwire.com","thehawkhilocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBZUQZNAWGBBVIMZ3M3HK6NW20MJQVPFNK",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
                "mediaType" : "Print",
                "CDNURL" :"http://cloud.thehawk.in/"
    },
    "delhiuptodate" : {
                "domains" : ["www.delhiuptodate.com","delhiuptodatesite.vocalwire.com","delhiuptodate.com","delhiuptodatesite.hocalwire.com","www.delhiuptodatesite.hocalwire.com","www.delhiuptodatesite.vocalwire.com","delhiuptodatesite.allytechnologies.in","www.delhiuptodatesite.allytechnologies.in","delhiuptodatelocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBPTMFME3UDUZSBWNOD8V1EQI06RBBWXXU",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "contentTypes" : ["survey"],
                "hasAuthors" : true,
                "mediaType" : "Online"
                
    },
    "presense" : {
                "domains" : ["www.digitalpresense.com","presensesite.vocalwire.com","digitalpresense.com","presensesite.hocalwire.com","www.presensesite.hocalwire.com","www.presensesite.vocalwire.com","presenselocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB0PLQCJBXNW1OAUI076BHPEQSVIQCI3FC",//RDWEBHWAQLT6MD9PUP8OMXCKJBPBP7XDFJIQN",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
            "mediaType" : "Online",
            "CDNURL" : "http://cloud.digitalpresense.com/"
    },
    "stylekandy" : {
                "domains" : ["stylekandysite.vocalwire.com","stylekandy.com","www.stylekandy.com","stylekandysite.hocalwire.com","www.stylekandysite.hocalwire.com","www.stylekandysite.vocalwire.com","stylekandylocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBWIEQIASLKNIXQGJKHH80DR5SRM8NIAAD",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Online"
    },
    "allytech" : {
                "domains" : ["hocalwire.com","www.hocalwire.com","allytechsite.hocalwire.com","allytechsite.vocalwire.com","allytechlocal.com","allytechnologies.in","www.allytechnologies.in"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBHGQTDN3Y9FASL8LVDTR7BTA4HIRZ2QQZ",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "contentTypes" : ["hocalpartners","adleads"],
                "cache" : false,
                "hasAuthors" : false
    },
    "mpost" : {
                "domains" : ["www.millenniumpost.in","millenniumpost.in","mpostsite.vocalwire.com","mpostlocal.com","mpostserversite.vocalwire.com","epaper.millenniumpost.in"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBKJRLYKW36V6OLPDMHP3TBHH9WUOJ9NZ5",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "contentTypes" : ["book","movie","photos"],
                "hasAuthors" : true,
                "mediaType" : "Print",
                "CDNURL" : "http://cloud.millenniumpost.in/"
    },
    "countryandpolitics" : {
                "domains" : ["countryandpoliticssite.vocalwire.com","countryandpolitics.in","www.countryandpolitics.in","countryandpoliticssite.hocalwire.com","www.countryandpoliticssite.hocalwire.com","www.countryandpoliticssite.vocalwire.com","countryandpoliticslocal.in"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBBEYAIYIKRPB10HSZFSRAMTRDSYB5YZ0F",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Online"
    },
    "smestreet" : {
                "domains" : ["smestreetsite.vocalwire.com","smestreetlocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBUYMRBKKPSF9H2J9NCGQOGWIUT7RWSIU3",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Paid"
    },
    "avnn" : {
                "domains" : ["avnn.in","www.avnnsite.hocalwire.com","avnnsite.hocalwire.com","avnn.in","avnnlocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB3U0QYCPVTFTAVIRCZ8S8LUAJOPJJO851",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,                
                "hasAuthors" : true,
                "mediaType" : "Online"
    },
    "tahlkanews" : {
                "domains" : ["tahlkanews.com","www.tahlkanewssite.vocalwire.com","tahlkanewssite.hocalwire.com","tahlkanewssite.vocalwire.com","tahlkanewslocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBICROG0AR5JISQ2NLUNUZKTNTLKGQ062V",//RDWEBICROG0AR5JISQ2NLUNUZKTNTLKGQ062V    RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
                "mediaType" : "Online",
                "contentTypes":["career"],

                "CDNURL" : "http://cloud.tahlkanews.com/"

    },
    "tahlkanewsen" : {
                "domains" : ["english.tahlkanews.com","tahlkanewsensite.hocalwire.com","tahlkanewsenlocal.com"],
                "langs" : ["hi"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBF0THUMFC3OURTJJGAX0NHUUTKMVID3LR",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : true,
                "mediaType" : "Online"
    },
    "publickhabar" : {
                "domains" : ["publickhabar.com","www.publickhabar.com","publickhabarsite.hocalwire.com", "www.publickhabarsite.hocalwire.com","publickhabarlocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBTHMUAXHDDAQHGNZDDAOT7WFVG1XEIP25",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
        "mediaType" : "Online"
    },
    "newschrome" : {
                "domains" : ["newschromesite.hocalwire.com", "newschrome.in","www.newschromesite.hocalwire.com","newschromelocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEBY5HZ3UNAKPSOXX9XE3AGHBC4UKQ7B8MT",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "mediaType" : "Online"
    },
    "smjl" : {
                "domains" : ["satyamevjayatelive.com", "smjlsite.hocalwire.com","smjllocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB3NU1RIT9QLMGPL0DQOWEYYERANM6RIIR",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "CDNURL" : "http://cloud.satyamevjayatelive.com/",
                "staticCacheUrls" : "",
                "cache" : false,
                "hasAuthors" : false,
                "mediaType" : "Online"
    },
    "thamarai" : {
                "domains" : ["thamaraisite.vocalwire.com","thamaraisite.hocalwire.com","www.thamaraisite.vocalwire.com","www.thamaraisite.hocalwire.com","thamarailocal.com"],
                "langs" : ["en"],
                "protocals" : ["http"],
                "sessionId" : "RDWEB2WNLS95LTF5NZT8E3YQJXOXSMHK8TAXB",//RDWEBGXEKT0X8MFVUQ3EDQYP4OIEYUVWNXNHB",
                "cacheRegex" : '/news/[\\w]*\\-([0-9]+)',
                "staticCacheUrls" : "",
                "contentTypes" : ["reporter","test_form"],
                "cache" : false,
                "hasAuthors" : false,
                "mediaType" : "Online"
    },
    "newsbuzz" : {
            "domains" : ["newsbuzz.co.in","www.newsbuzz.co.in","newsbuzzsite.vocalwire.com","newsbuzzsite.allytechnologies.in","newsbuzzsite.hocalwire.com","newsbuzzlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBE2R5KQAXRKK5K2KMMCXLGY7QT2FL6CWH",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "ficci" : {
            "domains" : ["ficci.com","www.ficci.com","ficcisite.vocalwire.com","ficcisite.hocalwire.com","ficcilocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB9ZYKKC3JGDSB3ONUHK6VAHBPNJQDHVI3",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "naradanews" : {
            "domains" : ["naradanews.com","www.naradanews.com","naradanewssite.vocalwire.com","naradanewssite.hocalwire.com","naradanewssite.allytechnologies.in","naradanewslocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBSUY4FAOFFKABXVXKTYRPOGLEZLIPFK2Q",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true,
    },
    "naradanewshi" : {
            "domains" : ["hi.naradanews.com","www.hi.naradanews.com","naradanewshisite.vocalwire.com","naradanewshisite.hocalwire.com","naradanewshisite.allytechnologies.in","naradanewshilocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBMJTKMLMOZMML1NOSAZ9HQGGRQCXLCYN1",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true,
    },
    "naradanewsml" : {
            "domains" : ["ml.naradanews.com","www.ml.naradanews.com","naradanewsmlsite.vocalwire.com","naradanewsmlsite.hocalwire.com","naradanewsmlsite.allytechnologies.in","naradanewsmllocal.com"],
            "langs" : ["ml"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJFRIUGHZKTRWLQIW4OHFPEEIFVDS7SUD",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true,
    },
    "dpratap" : {
            "domains" : ["dailypratap.com","www.dailypratap.com","dpratapsite.allytechnologies.in","dpratapsite.vocalwire.com","dpratapsite.hocalwire.com","www.dpratapsite.hocalwire.com","dprataplocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBU2ALSTZH25LOTYS1OU0EGSECV47ELYFI",
            
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true,
    },
    "dpratapurdu" : {
            "domains" : ["urdu.dailypratap.com","www.urdu.dailypratap.com","dpratapurdusite.allytechnologies.com","dpratapurdusite.vocalwire.com","dpratapurdusite.allytechnologies.in","www.dpratapurdusite.hocalwire.com","dpratapurdulocal.com"],
            "langs" : ["ur"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBHFPTT32A3FHCO8D9PS3KF1XZSUTRSARE",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true,
    },
    "virarjun" : {
            "domains" : ["www.virarjun.com","virarjun.com","virarjunsite.vocalwire.com","www.virarjunsite.vocalwire.com","virarjunsite.hocalwire.com","www.virarjunsite.hocalwire.com","www.virarjunsite.allytechnologies.in","virarjunsite.allytechnologies.in","virarjunlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBZWW5SQY8BTYPNA3CWRUH3HEDVHZDDWHT",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "sudarshan" : {
            "domains" : ["www.sudarshannews.com","sudarshannews.com","sudarshansite.vocalwire.com","sudarshansite.vocalwire.com","www.sudarshansite.vocalwire.com","sudarshansite.hocalwire.com","www.sudarshansite.hocalwire.com","sudarshanlocal.com","www.sudarshantv.com","sudarshantv.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJHZ9MXR2JAIR0WWG3I2UPEMYVI14FXEH",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "CDNURL" : "http://cloud.sudarshannews.com/",
            "cache" : false
    },
    "ranchiexpress" : {
            "domains" : ["ranchiexpress.com","www.ranchiexpress.com","ranchiexpresssite.vocalwire.com","www.ranchiexpresssite.vocalwire.com","ranchiexpresssite.allytechnologies.in","www.ranchiexpresssite.allytechnologies.in","ranchiexpresslocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBH7TKS7QWP8OSZOX83RA4HZANTZSS40PC",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["photos"],
            "CDNURL" : "http://cloud.ranchiexpress.com/",
            "hasAuthors" : true,
            "cache" : false
    },
    "rdigest" : {
            "domains" : ["www.resourcedigest.info","resourcedigest.info","rdigestsite.millenniumpost.in","www.rdigestsite.millenniumpost.in","rdigestlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBMHBNI5TDPSD6Z9DEORURSSIOMFQP699R",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "kshc" : {
            "domains" : ["www.krishansudamahealthcare.com","krishansudamahealthcare.com","www.krishansudamahealth.com","krishansudamahealth.com","kshcsite.allytechnologies.in","kshclocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBAWI3ZVTA2ISW8HCORYELQI6BFIZ0BAFM",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "news4thepeople" : {
            "domains" : ["news4thepeople.com","www.news4thepeople.com","news4thepeoplesite.vocalwire.com","news4thepeoplesite.vocalwire.com","news4thepeoplesite.allytechnologies.in","news4thepeoplesite.allytechnologies.in","news4thepeoplelocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJSQTEEJHQHP0Q0J3UGQY33UGWCIV3EHX",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "amarsir" : {
            "domains" : ["www.amarsir.com","amarsirsite.hocalwire.com","amarsirsite.vocalwire.com","amarsirsite.allytechnologies.in","amarsirsite.allytechnologies.in","amarsirlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB1R8BFJFRZYXZEWTZRYXI7FNOFBGTAVHG",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "pninews" : {
            "domains" : ["www.pninews.com","pninews.com","pninewssite.vocalwire.com","pninewslocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBRVATPEJFOX9BCWF1QBXWOLUSQOUQRTKZ",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasLogin":true
    },
    "pninewshi" : {
            "domains" : ["hi.pninews.com","hindi.pninews.com","pninewshisite.vocalwire.com","pninewshilocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBYZXPJXCGY3HAVKALO9MMBX8QDKJQMHZG",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsbn" : {
            "domains" : ["bn.pninews.com","bengali.pninews.com","pninewsbnsite.vocalwire.com","pninewsbnlocal.com"],
            "langs" : ["bn"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBPAKLOGNVMSGPIB4PDULZKWPBCQ8MT4DC",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsur" : {
            "domains" : ["ur.pninews.com","urdu.pninews.com","pninewsursite.vocalwire.com","pninewsurlocal.com"],
            "langs" : ["ur"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBGACKZ9LVKMIHO9HQNJ0PHZWNOS54P2WH",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsta" : {
            "domains" : ["ta.pninews.com","tamil.pninews.com","pninewstasite.vocalwire.com","pninewstalocal.com"],
            "langs" : ["ta"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBGAU1JATCGP1WGB13KPUXWLQTMGJXCXOQ",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewska" : {
            "domains" : ["ka.pninews.com","kannada.pninews.com","pninewskasite.vocalwire.com","pninewskalocal.com"],
            "langs" : ["ka"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJXBRL0LF7ONLG5BXKFHOADVY7CV6KKAM",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsma" : {
            "domains" : ["malayalam.pninews.com","ma.pninews.com","malyalam.pninews.com","pninewsmasite.vocalwire.com","pninewsmalocal.com"],
            "langs" : ["ma"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBVUYAYOG8LU1FGHVO5D85GTWPL1IJ4LOS",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsmr" : {
            "domains" : ["mr.pninews.com","marathi.pninews.com","pninewsmrsite.vocalwire.com","pninewsmrlocal.com"],
            "langs" : ["mr"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBIUCS7KWLLBR1KNRRETRQV1FROIDXUT35",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsasm" : {
            "domains" : ["assamese.pninews.com","asm.pninews.com","pninewsasmsite.vocalwire.com","pninewsasmlocal.com"],
            "langs" : ["asm"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBUDGZGTCSWEFVUCFMTAVNVVTFHHYBVXKO",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewste" : {
            "domains" : ["te.pninews.com","telgu.pninews.com","pninewstesite.vocalwire.com","pninewstelocal.com"],
            "langs" : ["te"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBYWCH3ORCPOGXPOI3SVRO4QMMH7K6SQUI",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsguj" : {
            "domains" : ["gujarati.pninews.com","guj.pninews.com","gujrati.pninews.com","pninewsgujsite.vocalwire.com","pninewsgujlocal.com"],
            "langs" : ["guj"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBDVDBWC7ANDKH83IMVID2L34ICWFYRWDN",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewsbho" : {
            "domains" : ["bho.pninews.com","bhojpuri.pninews.com","pninewsbhosite.vocalwire.com","pninewsbholocal.com"],
            "langs" : ["bho"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBA3UQCRTU2HTYJFF2EHS0N1P4PU0RFMFD",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "pninewspa" : {
            "domains" : ["pa.pninews.com","punjabi.pninews.com","pninewspasite.vocalwire.com","pninewspalocal.com"],
            "langs" : ["pa"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBAESREFIFFI2DMYCHOVYL0IXJ00AMDOMD",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "parentPartner" : "pninews",
            "hasLogin":true
    },
    "bfirst" : {
            "domains" : ["www.bfirst.in","bfirstsite.vocalwire.com","bfirstsite.hocalwire.com","www.bfirst.in","bfirstlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDANDROIDHOCALBFIRST869649021903574",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true
    },
    "janshakti" : {
            "domains" : ["www.janshakti.co.in","janshakti.co.in","janshaktisite.hocalwire.com","janshaktilocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBCNDDPWWG4MXJLRIRP1VTRRF6YVGQEOWH",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "contentTypes": ["poll","photos"],
            "CDNURL" : "http://cloud.janshakti.co.in/",
            "contentPreaLoadData" : ["poll"],
            "cache" : false
    },
    "janshaktien" : {
            "domains" : ["english.janshakti.co.in","en.janshakti.co.in","janshaktienlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBZHRJ4EOURDOXCXJQI4TVXKURZRFYPB4G",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "contentTypes": ["poll","photos"],
            "CDNURL" : "http://cloud.janshakti.co.in/",
            "contentPreaLoadData" : ["poll"],
            "cache" : false
    },
    "wtnstatic" : {
            "domains" : ["wtnstaticsite.hocalwire.com","wtnstaticlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB4MPUTURTJCAWDJLIIHP4XEYMMBPWGHBQ",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "contentTypes" : ["joinus"],
            "cache" : false
    },
    "internal" : {
            "domains" : ["internalsite.allytechnologies.in","internallocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBXCP14ZQOH9WLEVTMX0EIUNUEQVGF0BNL",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false
    },
    "samacharvaarta" : {
            "domains" : ["www.samacharvaarta.com","samacharvaarta.com","samacharvaartasite.vocalwire.com","www.samacharvaarta.com","samacharvaartalocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBD3HSTUPQZMMPWO9KIIGCXIAVIUFHHIIP",//-RDWEBD3HSTUPQZMMPWO9KIIGCXIAVIUFHHIIP   RDWEBNQLJL690BOJAZOZSWGRI2XAMTLTUPHNA
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes": ["poll"],
            "contentPreaLoadData" : ["poll"],
            "cache" : false,
            "hasAuthors" : true,
            "hasLogin":true
    },
    "nujindia" : {
            "domains" : ["nujindia.com","www.nujindia.com","nujindiasite.hocalwire.com","nujindialocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBS5IEM7JJWZAODDVKGMLVDLSPGY3CYFPD",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasLogin":true
    },
    "apnnews" : {
            "domains" : ["www.apnnews.com","apnnews.com","apnnewssite.vocalwire.com","apnnewslocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBTG8YNYWHFJSMZMYYOYROEAZUTLWIBQXY",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["photos"],
            "cache" : false,
            "hasAuthors" : true,
            "hasLogin":true
    }, 
    "apnnewshi" : {
            "domains" : ["apnsamachar.com","hindi.apnnews.com","hi.apnnews.com","apnnewhissite.vocalwire.com","apnnewshilocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB6AS0EYE7U5FVA6F57JB4MEN8C1D5VVQY",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["photos"],
            "cache" : false,
            "hasAuthors" : true,
            "hasLogin":true
    },
    "apnnewsml" : {
            "domains" : ["ml.apnnews.com","malayalam.apnnews.com","apnnewsmllocal.com"],
            "langs" : ["ml"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBDMY1XYKLYDXVPQM83A9R3XYJTKYPFO0M",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["photos"],
            "cache" : false,
            "hasAuthors" : true,
            "hasLogin":true
    },
    "bfirstka" : {
            "domains" : ["kannada.bfirst.in","bfirstkasite.hocalwire.com","bfirstkasite.hocalwire.com","bfirstkalocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBOS9J14D5F5NSEY0IWOCFOHQ9FV4JLEIE",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "cache" : false,
            "hasAuthors" : true
    },
    "sudarshanrelief" : {
            "domains" : ["sudarshanreliefsite.vocalwire.com","sudarshanrelieflocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBOJIPQAYXDPNLJJPFRAEAYIJ9ATITCENS",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "savecow" : {
            "domains" : ["www.savecow.co","savecow.co","savecowsite.vocalwire.com","savecowlocal.com","savecowsite.sudarshannews.com","wwww.savecowsite.sudarshannews.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJDEV3FWPYYHZ8DWRF9RXQU96CDTHDEOG",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "rastranirman" : {
            "domains" : ["www.rashtranirman.org","rashtranirman.org","rastranirmansite.vocalwire.com","rastranirmanlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBURQRD0VXIB4JRGKA3OSXPLREFZA4PGR6",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false

    },
    "sudarshannewsen" : {
            "domains" : ["english.sudarshannews.com","en.sudarshannews.com","english.sudarshantv.com","en.sudarshantv.com","sudarshannewsenlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBONDSIAQD7CFFGLY2KORDYQPNXNWMHXQA",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "sudarshannewsmar" : {
            "domains" : ["marathi.sudarshannews.com","mar.sudarshannews.com","marathi.sudarshantv.com","mar.sudarshantv.com","sudarshannewsmarlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBR2E0VZS8CJMMC44TUOLOX3GIWF1QWWAY",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "isj" : {
            "domains" : ["www.indiansciencejournal.in","indiansciencejournal.in","isjsite.hocalwire.com","isjlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBMYCW5VLX2G6O538SPTTSX1UPUWJHKTXM",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "skillindia" : {
            "domains" : ["skillindiapost.com","www.skillindiapost.com","www.skillindiapost.in","skillindiapost.in","skillindiasite.allytechnologies.in","skillindialocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBMOTU7IY5GTU4EPDXD0455ZQJHHELK7LF",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "banijya" : {
            "domains" : ["www.banijyasangbad.com","banijyasangbad.com","banijyasangbadlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBOQIFBFMJWWNBS9G5TZVSOXNDMPONZ9UW",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["applicationForm"],
            "hasAuthors" : true,
            "cache" : false
    },
    "royal" : {

            "domains" : ["www.royalbulletin.com","royalbulletin.com","royalsite.vocalwire.com","royallocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBYXEJQEPWQYF6V2FGKWENYC8D81IT9NDI",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "CDNURL" : "http://cloud.royalbulletin.com/",
            "hasAuthors" : true,
            "cache" : false
    },
    "royalen" : {

            "domains" : ["www.royalbulletin.in","royalbulletin.in","royalensite.vocalwire.com","royalenlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBUKWMWI9J6MAQPBOHQS9RWZCNQ9DJFA3X",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "CDNURL" : "http://cloud.royalbulletin.in/",
            "hasAuthors" : true,
            "cache" : false
    },
    "thejugaali" : {

            "domains" : ["thejugali.com","www.thejugali.com","thejugaalisite.allytechnologies.in","thejugaalilocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBOBJGWYUFYVNQ3FSSFMLYXINZBSBO6W8F",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "sudarshannewsml" : {
            "domains" : ["malayalam.sudarshannews.com","ml.sudarshannews.com","malayalam.sudarshantv.com","ml.sudarshantv.com","sudarshannewsmllocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBJZTNK2E9SPR3FPHEG7TOCCFFKN3VWV3L",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "sudarshannewsbn" : {
            "domains" : ["bengali.sudarshannews.com","bn.sudarshannews.com","bengali.sudarshantv.com","bn.sudarshantv.com","sudarshannewsbnlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBQ7EAQUXFUFFIX9ZRFZZ469ETVLIOVFLZ",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "sudarshannewsguj" : {
            "domains" : ["gujrati.sudarshannews.com","guj.sudarshannews.com","gujrati.sudarshantv.com","guj.sudarshantv.com","sudarshannewsgujlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBOOJLSX98XBVAUVSQGY9FO6KBYYFB2O6J",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "contentTypes" : ["reporter","poll","volunteer","member"],
            "contentPreaLoadData" : ["poll"],
            "hasLogin" : true,
            "hasAuthors" : true,
            "cache" : false
    },
    "womeninnews" : {
            "domains" : ["www.womeninnews.in","womeninnews.in","womeninnewssite.allytechnologies.in","womeninnewslocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBDGXMEZNWO12OXPXNQGZMNCF0OWOLDL9S",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : false,
            "hasAuthors" : false,
            "cache" : false

    },
    "hocalnewsroom" : {
            "domains" : ["newsroom.hocalwire.com","hocalnewsroom.com","hocalnewsroomsite.allytechnologies.in","hocalnewsroomlocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB6GJOMAPXWIA5GJHJVNRWU5RH0CCG2SH6",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : false,
            "hasAuthors" : false,
            "cache" : false
    },
    "hocallive" : {
            "domains" : ["live.hocalwire.com","hocallivelocal.com"],
            "langs" : ["hi"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB498GQ8OFEZRBJUXLEKKQ4UF9GTUDBNHR",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasLogin" : false,
            "hasAuthors" : false,
            "cache" : false

    },
    "sparkicon" : {
            "domains" : ["www.sparkicon.com","sparkicon.com","sparkiconsite.vocalwire.com","sparkiconlocal.com","sparkiconsite.hocalwire.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB8SIHTMQMSMK9KDCOBF3R7JKLYNJL84NZ",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "metrominews" : {
            "domains" : ["www.metrolive.net","metrolive.net","www.metromalayalamnews.com","metromalayalamnews.com","metromalnewssite.allytechnologies.in","metromlnewslocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBV8DI1K5EXQLOUKKMG7XJFJAPQUUHJNRH",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "bharatkhabar" : {
            "domains" : ["bharatkhabarsite.hocalwire.com","www.bharatkhabarsite.hocalwire.com","bharatkhabarlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBPPNH2IYINLDM7WXP0ID8CLGK3JWW6COA",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "aapkikhabar" : {
            "domains" : ["baapkikhabarsite.hocalwire.com","www.aapkikhabarsite.hocalwire.com","aapkikhabarlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBCTDUTK9Q7ZQXVOSNMZIEVZUM68SR6HSP",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "doctor" : {
            "domains" : ["doctorsite.hocalwire.com","www.doctorsite.hocalwire.com","doctorlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB4ARVJW6YKZFGCUZZAQD09RWELCX9JFM3",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "khojinews" : {
            "domains" : ["www.khojinews.co.in","khojinews.co.in","khojinewssite.vocalwire.com","khojinewssite.hocalwire.com","khojinewslocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBYKSWKHSELEOFTVZWPIOOEWENZMCSWT4M",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "reportprime" : {
            "domains" : ["www.reportprime.com","reportprime.com","reportprimesite.vocalwire.com","reportprimesite.hocalwire.com","reportprimelocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBC7MZLK2CTGLUW04QGALZHWPVKHW7UA7U",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "uporg" : {
            "domains" : ["uporgsite.hocalwire.com","uporglocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEB1L9NHXODSDQIPLG2PINZHSGM20X8HUV6",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "contentTypes" : ["constituencyhindimp","vidhansabhahi","mprajyasabhahi","constituencyhindimla","mphindi","mpeng"],
            "cache" : false
    },
    "saisansthan" : {
            "domains" : ["saisansthansite.vocalwire.com","www.saisansthan.com","saisansthan.com","saisansthansite.hocalwire.com","saisansthanlocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBERNPM5B8QREXIJYEGLBEVALV6IHIFP9Z",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
    "amity" : {
            "domains" : ["amitysite.hocalwire.com","amitylocal.com"],
            "langs" : ["en"],
            "protocals" : ["http"],
            "sessionId" : "RDWEBELVD4NIKEUWLZKKTAPNNAOH9J0COE32O",
            "cacheRegex" : '/[\\w]*\\-([0-9]+)',
            "staticCacheUrls" : "/404,/error,/aboutus,/contactus",
            "hasAuthors" : true,
            "cache" : false
    },
};
module.exports = PartnerConfig;
